// Style registry. Each entry describes a complete invitation aesthetic
// (layout + palette + fonts + ornaments) and is implemented by a dedicated
// React component under ../components/styles/.
// The Style picker uses `swatch` for the gallery thumbnail.

export const STYLES = {
  cosmos: {
    id: 'cosmos',
    label: 'Cosmos',
    labelHe: 'קוסמי',
    family: 'animated',
    description: 'גלקסיה חיה — כוכבים, ערפיליות, 3D הטיה. בלתי-נשכח.',
    swatch: ['#0a0612', '#2a0a4a', '#e9c97a'],
    fonts: { display: 'font-display', body: 'font-hebrew', script: 'font-script' },
    background: 'cosmic',
    rtl: true,
  },
  classic: {
    id: 'classic',
    label: 'Classic',
    labelHe: 'קלאסי',
    family: 'static',
    description: 'נייר קרם, מסגרת זהב, אותיות סופרים. לא מהעולם הזה — מהעולם הנכון.',
    swatch: ['#f5ecd9', '#c9a75a', '#1a1308'],
    fonts: { display: 'font-display', body: 'font-hebrew', script: 'font-script' },
    background: 'paper-cream',
    rtl: true,
  },
  botanical: {
    id: 'botanical',
    label: 'Botanical',
    labelHe: 'בוטני',
    family: 'static',
    description: 'איורי צמחייה רכים, ירוק זית, גוון פסטל מרגיע.',
    swatch: ['#f3efe6', '#5a7a4a', '#9a6f3f'],
    fonts: { display: 'font-display', body: 'font-hebrew', script: 'font-script' },
    background: 'paper-sage',
    rtl: true,
  },
  editorial: {
    id: 'editorial',
    label: 'Editorial',
    labelHe: 'אדיטוריאל',
    family: 'static',
    description: 'מגזין עכשווי. טיפוגרפיה דרמטית, ניגודיות חזקה, אסימטריה.',
    swatch: ['#0e0e0e', '#fafafa', '#ff5436'],
    fonts: { display: 'font-display', body: 'font-hebrew', script: 'font-display' },
    background: 'split-bw',
    rtl: true,
  },
  artdeco: {
    id: 'artdeco',
    label: 'Art Deco',
    labelHe: 'אר-דקו',
    family: 'static',
    description: 'גטסבי. גיאומטריה מוזהבת, מניפות, ניצוצות שמפניה.',
    swatch: ['#0a1a2a', '#d4a017', '#f5e6b3'],
    fonts: { display: 'font-display', body: 'font-hebrew', script: 'font-display' },
    background: 'deco-navy',
    rtl: true,
  },
  minimalist: {
    id: 'minimalist',
    label: 'Minimalist',
    labelHe: 'מינימליסטי',
    family: 'static',
    description: 'הכל מיותר. רק מילים, רווחים, וקו אחד מלוטש.',
    swatch: ['#fafaf7', '#0a0a0a', '#a0a0a0'],
    fonts: { display: 'font-mono', body: 'font-hebrew', script: 'font-display' },
    background: 'paper-white',
    rtl: true,
  },
  mediterranean: {
    id: 'mediterranean',
    label: 'Mediterranean',
    labelHe: 'מדיטרני',
    family: 'static',
    description: 'טרקוטה, קשתות, אור אחר-צהריים על אבן ירושלמית.',
    swatch: ['#f3e3c8', '#c0633a', '#3a5a4a'],
    fonts: { display: 'font-display', body: 'font-hebrew', script: 'font-script' },
    background: 'arches-terracotta',
    rtl: true,
  },
  watercolor: {
    id: 'watercolor',
    label: 'Watercolor',
    labelHe: 'מים-צבע',
    family: 'animated',
    description: 'כתמי צבע רכים שזורמים. רומנטי בלי להיות מתקתק.',
    swatch: ['#fef6f3', '#e7a3a3', '#5a7a8a'],
    fonts: { display: 'font-script', body: 'font-hebrew', script: 'font-script' },
    background: 'watercolor',
    rtl: true,
  },
};

export const STYLE_LIST = Object.values(STYLES);
